version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/website"
    schedule:
      interval: "daily"
    # Raised limit temporarily to get all potential upgrades
    open-pull-requests-limit: 15
    groups:
      babel:
        patterns:
          - "@babel/core"
          - "@babel/preset-env"
          - "@types/babel__preset-env"
      docusaurus:
        patterns:
          - "@docusaurus/*"
      emotion:
        patterns:
          - "@emotion/*"
      eslint:
        patterns:
          - eslint
          - "@eslint/*"
          - "@typescript-eslint/*"
      mui:
        patterns:
          - "@mui/*"
      parcel:
        patterns:
          - parcel
          - "@parcel/*"
      react:
        patterns:
          - react
          - "react-*"
          - "@types/react"
          - "@types/react-*"
        exclude-patterns:
          - react-lottie-player
          - react-markdown
          - react-router
          - react-syntax-highlighter
          - react-toastify
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      golang-grpc:
        patterns:
          - google.golang.org/grpc
          - google.golang.org/protobuf
      golang-x:
        patterns:
          - "golang.org/x/*"
      kustomize:
        patterns:
          - "sigs.k8s.io/kustomize/*"
      k8s:
        patterns:
          - "k8s.io/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /website
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: daily
